import { expect, test, type Page } from '@playwright/test';

/**
 * T170 — quickstart V6, search (US6).
 *
 * ⚠️ Written and type-checked; not yet executed against a running stack, the same gap T106, T122,
 * T141, and T158 record for the whole suite (Compose images unbuilt — T013, T027).
 *
 * **Scope note, not a gap to close later.** Quickstart V6 says to run this against the seeded
 * full-retention corpus, and step 1's "results within 1 second" is a latency claim that belongs to
 * `tests/Load/search.js` — a browser measurement includes React rendering and would report a
 * different number against a different bar. What the browser adds, and what is scripted here, is
 * the part k6 cannot see: that a non-member's search is *indistinguishable from empty* in the UI,
 * that jump-to-context lands on the right message, and that the truncation notice is actually
 * shown. FR-033's whole point is that a person is told; a test that only checked the JSON field
 * would miss a UI that drops it.
 */

const MEMBER = 'an.nguyen';
const OTHER_MEMBER = 'binh.tran';
const NON_MEMBER = 'chi.le';

/** Distinctive enough that a match is unambiguous against seeded filler. */
const SHARED_PHRASE = 'aubergine provisioning schedule';
const PRIVATE_PHRASE = 'pomegranate reconciliation quarterly';

async function signIn(page: Page, username: string): Promise<void> {
  await page.goto('/');
  await page.getByLabel(/username|email/i).fill(username);
  await page.getByLabel(/password/i).fill(username);
  await page.getByRole('button', { name: /sign in|log in/i }).click();
  await expect(page.getByTestId('display-name')).toBeVisible();
}

async function openFirstConversation(page: Page): Promise<void> {
  await page.getByTestId('conversation-list').getByRole('button').first().click();
  await expect(page.getByTestId('message-list')).toBeVisible();
}

async function send(page: Page, body: string): Promise<void> {
  await page.getByTestId('composer-input').fill(body);
  await page.getByTestId('composer-send').click();
  await expect(page.getByTestId('message-list')).toContainText(body);
}

async function search(page: Page, phrase: string): Promise<void> {
  await page.getByTestId('search-input').fill(phrase);
}

test.describe('V6 — search', () => {
  test('a phrase from your own conversation is found, ranked, with context (step 1)', async ({
    page,
  }) => {
    await signIn(page, MEMBER);
    await openFirstConversation(page);
    await send(page, SHARED_PHRASE);

    await search(page, SHARED_PHRASE);

    const results = page.getByTestId('search-results');
    await expect(results.getByRole('listitem')).toHaveCount(1);

    // The snippet, not the whole message. `ts_headline` marks the match, and the UI renders that
    // marker — which is the only place this app renders server-supplied HTML.
    await expect(results.locator('mark').first()).toBeVisible();
  });

  test('a phrase that exists only in a conversation you are not in returns nothing (step 2)', async ({
    browser,
  }) => {
    const insiderContext = await browser.newContext();
    const outsiderContext = await browser.newContext();

    const insider = await insiderContext.newPage();
    const outsider = await outsiderContext.newPage();

    await signIn(insider, OTHER_MEMBER);
    await openFirstConversation(insider);
    await send(insider, PRIVATE_PHRASE);

    // The control: the phrase is genuinely there and genuinely findable by someone who may see it.
    await search(insider, PRIVATE_PHRASE);
    await expect(insider.getByTestId('search-results').getByRole('listitem')).toHaveCount(1);

    await signIn(outsider, NON_MEMBER);
    await search(outsider, PRIVATE_PHRASE);

    // Nothing — and nothing distinguishable from a phrase that exists nowhere at all.
    await expect(outsider.getByTestId('search-results').getByRole('listitem')).toHaveCount(0);
    await expect(outsider.getByText(/no messages match/i)).toBeVisible();

    await search(outsider, 'chrysanthemum triangulation sediment');
    await expect(outsider.getByText(/no messages match/i)).toBeVisible();

    await insiderContext.close();
    await outsiderContext.close();
  });

  test('editing a message removes its old text from results (step 3, FR-032)', async ({ page }) => {
    await signIn(page, MEMBER);
    await openFirstConversation(page);
    await send(page, SHARED_PHRASE);

    await search(page, SHARED_PHRASE);
    await expect(page.getByTestId('search-results').getByRole('listitem')).toHaveCount(1);

    await page.getByTestId('message-list').getByRole('button', { name: /edit/i }).last().click();
    await page.getByTestId('composer-input').fill('courgette provisioning schedule');
    await page.getByTestId('composer-send').click();

    // No stale hit. The vector is regenerated by the write itself, so this needs no wait beyond
    // the debounce — there is no re-indexing step to race.
    await search(page, SHARED_PHRASE);
    await expect(page.getByText(/no messages match/i)).toBeVisible();

    await search(page, 'courgette provisioning');
    await expect(page.getByTestId('search-results').getByRole('listitem')).toHaveCount(1);
  });

  test('a result jumps to its message in the original conversation (FR-031)', async ({ page }) => {
    await signIn(page, MEMBER);
    await openFirstConversation(page);
    await send(page, SHARED_PHRASE);

    // Push it out of view, so landing on it proves navigation rather than luck.
    for (let index = 0; index < 30; index++) {
      await send(page, `filler message ${String(index)}`);
    }

    await search(page, SHARED_PHRASE);
    await page.getByTestId('search-results').getByRole('button').first().click();

    // Back in the conversation, with the message on screen and marked.
    await expect(page.getByTestId('message-list')).toBeVisible();
    await expect(page.getByTestId('message-list')).toContainText(SHARED_PHRASE);
    await expect(page.getByTestId('jump-target')).toBeInViewport();
  });

  test('the attachment filter narrows to messages carrying one (FR-030)', async ({ page }) => {
    await signIn(page, MEMBER);
    await openFirstConversation(page);

    await send(page, `${SHARED_PHRASE} without a file`);

    await search(page, SHARED_PHRASE);
    await expect(page.getByTestId('search-results').getByRole('listitem')).toHaveCount(1);

    await page.getByLabel(/attachments/i).selectOption('any');

    // The same phrase, now filtered to messages with an attachment — of which there are none.
    await expect(page.getByText(/no messages match/i)).toBeVisible();
  });

  test('a truncated search says so rather than looking complete (FR-033)', async ({ page }) => {
    await signIn(page, MEMBER);

    // Truncation only happens when the search exceeds its 800 ms budget, which needs the seeded
    // corpus this scenario is meant to run against. Skipped rather than faked: forcing the flag by
    // stubbing the response would assert that the UI renders a prop, which React guarantees — the
    // claim worth testing is that a genuinely truncated search surfaces, and that needs real data.
    test.skip(
      process.env.SEEDED_CORPUS !== 'true',
      'Requires the full-retention corpus; run with SEEDED_CORPUS=true after seeding (T169).',
    );

    await search(page, 'a e i o u');

    await expect(page.getByTestId('search-truncated')).toBeVisible();
    await expect(page.getByTestId('search-truncated')).toContainText(/partial results/i);
  });
});
