namespace InternalChat.Application.Abstractions;

/// <summary>Free and used bytes in attachment storage.</summary>
/// <param name="UsedBytes">Bytes currently consumed by attachments.</param>
/// <param name="CapacityBytes">Total provisioned capacity.</param>
public readonly record struct StorageCapacity(long UsedBytes, long CapacityBytes)
{
    /// <summary>Fraction of capacity consumed, 0.0 to 1.0.</summary>
    public double UsedFraction => CapacityBytes <= 0 ? 1.0 : (double)UsedBytes / CapacityBytes;
}

/// <summary>
/// Attachment object storage (MinIO or any S3-compatible server).
/// </summary>
/// <remarks>
/// <para>
/// Note what is absent: there is no method returning a retrieval URL. That is deliberate.
/// FR-025 requires membership to be checked on every retrieval "regardless of how the retrieval
/// address was obtained", and a presigned download URL is a bearer capability — whoever holds it
/// gets the bytes, member or not. Handing one out would fail the requirement literally.
/// </para>
/// <para>
/// Retrieval instead goes through the API, which authorizes each request and then hands the byte
/// transfer to the reverse proxy by internal redirect (research.md D7). Uploads still use a
/// one-time ticket, because an upload address grants no read access and the object stays in
/// quarantine until ClamAV clears it.
/// </para>
/// </remarks>
public interface IObjectStore
{
    /// <summary>
    /// Reserves a one-time upload location in the quarantine bucket.
    /// </summary>
    /// <remarks>
    /// Nothing written here is retrievable by anyone. Promotion to the clean bucket happens only
    /// after a clean scan verdict (FR-024).
    /// </remarks>
    Task<Uri> CreateUploadTicketAsync(
        string objectKey,
        string contentType,
        long byteSize,
        TimeSpan validFor,
        CancellationToken cancellationToken = default);

    /// <summary>Moves a scanned-clean object from quarantine into the retrievable bucket.</summary>
    Task PromoteToCleanAsync(string objectKey, CancellationToken cancellationToken = default);

    /// <summary>
    /// Permanently removes an object — used for infected uploads, deleted messages, and the
    /// retention sweep.
    /// </summary>
    Task DeleteAsync(string objectKey, CancellationToken cancellationToken = default);

    /// <summary>Opens a read stream for the API to hand to the reverse proxy.</summary>
    Task<Stream> OpenReadAsync(string objectKey, CancellationToken cancellationToken = default);

    /// <summary>
    /// Opens a quarantined object so it can be scanned.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Separate from <see cref="OpenReadAsync"/> rather than a bucket parameter on it, because the
    /// two have opposite security properties and the distinction should be impossible to get wrong
    /// at a call site. <see cref="OpenReadAsync"/> serves bytes to a person and reads only the clean
    /// bucket; this one reads bytes nobody may see and exists for exactly one caller, the scan
    /// consumer. A single method taking a bucket name would put "which bucket?" into every call.
    /// </para>
    /// <para>
    /// Throws <see cref="IOException"/> when the object is not there — the ordinary interrupted-upload
    /// case (FR-026), which the consumer records as a failed scan rather than retrying forever.
    /// </para>
    /// </remarks>
    Task<Stream> OpenQuarantineReadAsync(string objectKey, CancellationToken cancellationToken = default);

    /// <summary>
    /// Overwrites a quarantined object in place.
    /// </summary>
    /// <remarks>
    /// Exists for exactly one caller: the faststart remux (research.md D8), which rewrites an MP4's
    /// index before promotion. It targets quarantine rather than the clean bucket on purpose — the
    /// remuxed bytes are still unpromoted at that point, and writing them to the clean bucket would
    /// put a retrievable object there before the row says clean, which is the ordering FR-024
    /// forbids.
    /// </remarks>
    Task ReplaceQuarantineObjectAsync(
        string objectKey,
        Stream content,
        string contentType,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Writes a derived object straight into the clean bucket.
    /// </summary>
    /// <remarks>
    /// <para>
    /// For video poster frames only, and safe for the same reason the general rule exists: a poster
    /// is generated by this system from bytes that have already passed their scan, so it is not
    /// unscanned user content. It bypasses quarantine because there is nothing to scan — sending
    /// our own output back through ClamAV would be scanning ffmpeg rather than the upload.
    /// </para>
    /// <para>
    /// Deliberately narrow, and the narrowness is the point: a general "write to the clean bucket"
    /// method is one careless call away from being the hole the two-bucket split exists to prevent.
    /// </para>
    /// </remarks>
    Task PutCleanObjectAsync(
        string objectKey,
        Stream content,
        string contentType,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Current capacity, so administrators are alerted before uploads start failing (FR-028).
    /// </summary>
    Task<StorageCapacity> GetCapacityAsync(CancellationToken cancellationToken = default);
}
