// <auto-generated />
using System;
using System.Net;
using InternalChat.Domain.Conversations;
using InternalChat.Domain.Employees;
using InternalChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternalChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260813044256_ConversationAndMessage")]
    partial class ConversationAndMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "conversation_kind", new[] { "direct", "group" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_status", new[] { "active", "deactivated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "history_visibility", new[] { "from_join", "full" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "membership_role", new[] { "admin", "member" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternalChat.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DirectKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("direct_key");

                    b.Property<HistoryVisibility>("HistoryVisibility")
                        .HasColumnType("history_visibility")
                        .HasColumnName("history_visibility");

                    b.Property<ConversationKind>("Kind")
                        .HasColumnType("conversation_kind")
                        .HasColumnName("kind");

                    b.Property<long>("LastSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_seq");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_conversation_created_by");

                    b.HasIndex("DirectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_direct_key")
                        .HasFilter("kind = 'direct'");

                    b.ToTable("conversation", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversation_direct_shape", "(kind = 'direct' AND name IS NULL AND direct_key IS NOT NULL) OR (kind = 'group' AND direct_key IS NULL)");

                            t.HasCheckConstraint("ck_conversation_group_has_name", "kind <> 'group' OR (name IS NOT NULL AND length(btrim(name)) > 0)");
                        });
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Membership", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("MutedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("muted_until");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("removed_at");

                    b.Property<MembershipRole>("Role")
                        .HasColumnType("membership_role")
                        .HasColumnName("role");

                    b.Property<long>("VisibleFromSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("visible_from_seq");

                    b.HasKey("ConversationId", "EmployeeId")
                        .HasName("pk_membership");

                    b.HasIndex("ConversationId", "EmployeeId")
                        .HasDatabaseName("ix_membership_active_lookup")
                        .HasFilter("removed_at IS NULL");

                    b.HasIndex("EmployeeId", "RemovedAt")
                        .HasDatabaseName("ix_membership_employee_removed");

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subject");

                    b.Property<EmployeeStatus>("Status")
                        .HasColumnType("employee_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_employee_display_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DisplayName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_email");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_external_subject");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<string>("ClientMessageKey")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("client_message_key");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("edited_at");

                    b.PrimitiveCollection<Guid[]>("Mentions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("mentions")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.HasKey("Id", "SentAt")
                        .HasName("pk_message");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_message_author_id");

                    b.HasIndex("ConversationId", "Seq")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_message_conversation_seq");

                    b.ToTable("message", null, t =>
                        {
                            t.HasCheckConstraint("ck_message_body_length", "body IS NULL OR (length(body) BETWEEN 1 AND 8000)");

                            t.HasCheckConstraint("ck_message_body_or_tombstone", "(deleted_at IS NULL AND body IS NOT NULL) OR (deleted_at IS NOT NULL AND body IS NULL)");

                            t.HasCheckConstraint("ck_message_seq_positive", "seq >= 1");
                        });
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Audit.AuditEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_event_actor");

                    b.HasIndex("SubjectType", "SubjectId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_event_subject");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_outcome", "outcome IN ('success', 'denied', 'error')");
                        });
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Messages.MessageDeduplicationRecord", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ClientMessageKey")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("client_message_key");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.HasKey("ConversationId", "ClientMessageKey")
                        .HasName("pk_message_dedup");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_message_dedup_sent_at");

                    b.ToTable("message_dedup", (string)null);
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("routing_key");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Outbox.ProcessedMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("ConsumerName", "MessageId")
                        .HasName("pk_processed_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_message_processed_at");

                    b.ToTable("processed_message", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Conversation", b =>
                {
                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_employee_created_by");
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Membership", b =>
                {
                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_conversation_conversation_id");

                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_employee_employee_id");
                });

            modelBuilder.Entity("InternalChat.Domain.Messages.Message", b =>
                {
                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_employee_author_id");

                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_conversation_conversation_id");
                });
#pragma warning restore 612, 618
        }
    }
}
