// <auto-generated />
using System;
using System.Net;
using InternalChat.Domain.Attachments;
using InternalChat.Domain.Conversations;
using InternalChat.Domain.Employees;
using InternalChat.Domain.Meetings;
using InternalChat.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InternalChat.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "attachment_kind", new[] { "image", "video" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "conversation_kind", new[] { "direct", "group" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "employee_status", new[] { "active", "deactivated" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "history_visibility", new[] { "from_join", "full" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "membership_role", new[] { "admin", "member" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "scan_status", new[] { "clean", "failed", "infected", "pending" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "share_scope", new[] { "screen", "window" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "share_stop_reason", new[] { "meeting_ended", "participant_left", "stopped", "superseded" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InternalChat.Domain.Attachments.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<AttachmentKind>("Kind")
                        .HasColumnType("attachment_kind")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset?>("MessageSentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("message_sent_at");

                    b.Property<string>("PosterObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("poster_object_key");

                    b.Property<ScanVerdict>("ScanStatus")
                        .HasColumnType("scan_status")
                        .HasColumnName("scan_status");

                    b.Property<DateTimeOffset?>("ScannedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("scanned_at");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("pk_attachment");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_attachment_conversation");

                    b.HasIndex("MessageId")
                        .HasDatabaseName("ix_attachment_message")
                        .HasFilter("message_id IS NOT NULL");

                    b.HasIndex("ScanStatus")
                        .HasDatabaseName("ix_attachment_pending_scan")
                        .HasFilter("scan_status = 'pending'");

                    b.HasIndex("UploadedBy")
                        .HasDatabaseName("ix_attachment_uploaded_by");

                    b.ToTable("attachment", null, t =>
                        {
                            t.HasCheckConstraint("ck_attachment_byte_size", "byte_size > 0 AND (\r\n    (kind = 'image' AND byte_size <= 26214400)\r\n OR (kind = 'video' AND byte_size <= 524288000))");

                            t.HasCheckConstraint("ck_attachment_duration", "(kind = 'video' AND duration_seconds IS NOT NULL\r\n     AND duration_seconds BETWEEN 1 AND 600)\r\nOR (kind <> 'video' AND duration_seconds IS NULL)");

                            t.HasCheckConstraint("ck_attachment_message_reference", "(message_id IS NULL) = (message_sent_at IS NULL)");

                            t.HasCheckConstraint("ck_attachment_poster_is_video", "poster_object_key IS NULL OR kind = 'video'");

                            t.HasCheckConstraint("ck_attachment_scanned_at", "(scan_status = 'pending') = (scanned_at IS NULL)");
                        });
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DirectKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("direct_key");

                    b.Property<HistoryVisibility>("HistoryVisibility")
                        .HasColumnType("history_visibility")
                        .HasColumnName("history_visibility");

                    b.Property<ConversationKind>("Kind")
                        .HasColumnType("conversation_kind")
                        .HasColumnName("kind");

                    b.Property<long>("LastSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("last_seq");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_conversation");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_conversation_created_by");

                    b.HasIndex("DirectKey")
                        .IsUnique()
                        .HasDatabaseName("ux_conversation_direct_key")
                        .HasFilter("kind = 'direct'");

                    b.ToTable("conversation", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversation_direct_shape", "(kind = 'direct' AND name IS NULL AND direct_key IS NOT NULL) OR (kind = 'group' AND direct_key IS NULL)");

                            t.HasCheckConstraint("ck_conversation_group_has_name", "kind <> 'group' OR (name IS NOT NULL AND length(btrim(name)) > 0)");
                        });
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Membership", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("MutedUntil")
                        .HasColumnType("timestamptz")
                        .HasColumnName("muted_until");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("removed_at");

                    b.Property<MembershipRole>("Role")
                        .HasColumnType("membership_role")
                        .HasColumnName("role");

                    b.Property<long>("VisibleFromSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("visible_from_seq");

                    b.HasKey("ConversationId", "EmployeeId")
                        .HasName("pk_membership");

                    b.HasIndex("ConversationId", "EmployeeId")
                        .HasDatabaseName("ix_membership_active_lookup")
                        .HasFilter("removed_at IS NULL");

                    b.HasIndex("EmployeeId", "RemovedAt")
                        .HasDatabaseName("ix_membership_employee_removed");

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("ExternalSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_subject");

                    b.Property<EmployeeStatus>("Status")
                        .HasColumnType("employee_status")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_employee");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_employee_display_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DisplayName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DisplayName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_email");

                    b.HasIndex("ExternalSubject")
                        .IsUnique()
                        .HasDatabaseName("ix_employee_external_subject");

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Meetings.Meeting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ended_at");

                    b.Property<int>("PeakParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("peak_participants");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<Guid>("StartedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("started_by");

                    b.HasKey("Id")
                        .HasName("pk_meeting");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_meeting_active_by_conversation")
                        .HasFilter("ended_at IS NULL");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_meeting_started_at");

                    b.HasIndex("StartedBy")
                        .HasDatabaseName("ix_meeting_started_by");

                    b.ToTable("meeting", null, t =>
                        {
                            t.HasCheckConstraint("ck_meeting_ends_after_start", "ended_at IS NULL OR ended_at >= started_at");

                            t.HasCheckConstraint("ck_meeting_peak_participants", "peak_participants >= 0 AND peak_participants <= 25");
                        });
                });

            modelBuilder.Entity("InternalChat.Domain.Meetings.ShareSession", b =>
                {
                    b.Property<Guid>("MeetingId")
                        .HasColumnType("uuid")
                        .HasColumnName("meeting_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<ShareScope>("Scope")
                        .HasColumnType("share_scope")
                        .HasColumnName("scope");

                    b.Property<ShareStopReason?>("StopReason")
                        .HasColumnType("share_stop_reason")
                        .HasColumnName("stop_reason");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("stopped_at");

                    b.HasKey("MeetingId", "EmployeeId", "StartedAt")
                        .HasName("pk_share_session");

                    b.HasIndex("MeetingId")
                        .IsUnique()
                        .HasDatabaseName("ux_share_session_one_active_per_meeting")
                        .HasFilter("stopped_at IS NULL");

                    b.ToTable("share_session", null, t =>
                        {
                            t.HasCheckConstraint("ck_share_session_stop_reason", "(stopped_at IS NULL) = (stop_reason IS NULL)");

                            t.HasCheckConstraint("ck_share_session_stops_after_start", "stopped_at IS NULL OR stopped_at >= started_at");
                        });
                });

            modelBuilder.Entity("InternalChat.Domain.Messages.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("body");

                    b.Property<string>("ClientMessageKey")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("client_message_key");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("edited_at");

                    b.PrimitiveCollection<Guid[]>("Mentions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("mentions")
                        .HasDefaultValueSql("'{}'::uuid[]");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.HasKey("Id", "SentAt")
                        .HasName("pk_message");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_message_author_id");

                    b.HasIndex("ConversationId", "Seq")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_message_conversation_seq");

                    b.ToTable("message", null, t =>
                        {
                            t.HasCheckConstraint("ck_message_body_length", "body IS NULL OR (length(body) BETWEEN 1 AND 8000)");

                            t.HasCheckConstraint("ck_message_body_or_tombstone", "(deleted_at IS NULL AND body IS NOT NULL) OR (deleted_at IS NOT NULL AND body IS NULL)");

                            t.HasCheckConstraint("ck_message_seq_positive", "seq >= 1");
                        });
                });

            modelBuilder.Entity("InternalChat.Domain.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<int>("DigestAfterMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("digest_after_minutes");

                    b.Property<TimeOnly?>("DndEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("dnd_end");

                    b.Property<TimeOnly?>("DndStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("dnd_start");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("EmployeeId")
                        .HasName("pk_notification_preference");

                    b.ToTable("notification_preference", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Notifications.ReadState", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<long>("LastReadSeq")
                        .HasColumnType("bigint")
                        .HasColumnName("last_read_seq");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("EmployeeId", "ConversationId")
                        .HasName("pk_read_state");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_read_state_conversation_id");

                    b.ToTable("read_state", (string)null);
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Audit.AuditEventRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<IPAddress>("SourceIp")
                        .HasColumnType("inet")
                        .HasColumnName("source_ip");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("ActorId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_event_actor");

                    b.HasIndex("SubjectType", "SubjectId", "OccurredAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_audit_event_subject");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_outcome", "outcome IN ('success', 'denied', 'error')");
                        });
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Messages.MessageDeduplicationRecord", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ClientMessageKey")
                        .HasMaxLength(26)
                        .HasColumnType("character varying(26)")
                        .HasColumnName("client_message_key");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.HasKey("ConversationId", "ClientMessageKey")
                        .HasName("pk_message_dedup");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_message_dedup_sent_at");

                    b.ToTable("message_dedup", (string)null);
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Notifications.PushSubscriptionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("endpoint");

                    b.Property<DateTimeOffset?>("LastSuccessAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_success_at");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("p256dh");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_push_subscription");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_push_subscription_employee");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ix_push_subscription_endpoint");

                    b.ToTable("push_subscription", (string)null);
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("routing_key");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_parent");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_message_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("outbox_message", (string)null);
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Outbox.ProcessedMessage", b =>
                {
                    b.Property<string>("ConsumerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer_name");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.HasKey("ConsumerName", "MessageId")
                        .HasName("pk_processed_message");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("ix_processed_message_processed_at");

                    b.ToTable("processed_message", (string)null);
                });

            modelBuilder.Entity("InternalChat.Domain.Attachments.Attachment", b =>
                {
                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachment_conversation_conversation_id");

                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachment_employee_uploaded_by");
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Conversation", b =>
                {
                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_employee_created_by");
                });

            modelBuilder.Entity("InternalChat.Domain.Conversations.Membership", b =>
                {
                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_conversation_conversation_id");

                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_membership_employee_employee_id");
                });

            modelBuilder.Entity("InternalChat.Domain.Meetings.Meeting", b =>
                {
                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meeting_conversation_conversation_id");

                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("StartedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_meeting_employee_started_by");

                    b.OwnsMany("InternalChat.Domain.Meetings.Participation", "Participants", b1 =>
                        {
                            b1.Property<Guid>("MeetingId")
                                .HasColumnType("uuid")
                                .HasColumnName("meeting_id");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("employee_id");

                            b1.Property<DateTimeOffset>("JoinedAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("joined_at");

                            b1.Property<DateTimeOffset?>("LeftAt")
                                .HasColumnType("timestamptz")
                                .HasColumnName("left_at");

                            b1.Property<int>("SharedScreenSeconds")
                                .HasColumnType("integer")
                                .HasColumnName("shared_screen_seconds");

                            b1.HasKey("MeetingId", "EmployeeId")
                                .HasName("pk_participation");

                            b1.HasIndex("EmployeeId")
                                .HasDatabaseName("ix_participation_employee");

                            b1.ToTable("participation", null, t =>
                                {
                                    t.HasCheckConstraint("ck_participation_leaves_after_join", "left_at IS NULL OR left_at >= joined_at");

                                    t.HasCheckConstraint("ck_participation_share_seconds", "shared_screen_seconds >= 0");
                                });

                            b1.HasOne("InternalChat.Domain.Employees.Employee", null)
                                .WithMany()
                                .HasForeignKey("EmployeeId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_participation_employee_employee_id");

                            b1.WithOwner()
                                .HasForeignKey("MeetingId")
                                .HasConstraintName("fk_participation_meeting_meeting_id");
                        });

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("InternalChat.Domain.Meetings.ShareSession", b =>
                {
                    b.HasOne("InternalChat.Domain.Meetings.Meeting", null)
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_share_session_meeting_meeting_id");
                });

            modelBuilder.Entity("InternalChat.Domain.Messages.Message", b =>
                {
                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_employee_author_id");

                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_conversation_conversation_id");
                });

            modelBuilder.Entity("InternalChat.Domain.Notifications.NotificationPreference", b =>
                {
                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_preference_employee_employee_id");
                });

            modelBuilder.Entity("InternalChat.Domain.Notifications.ReadState", b =>
                {
                    b.HasOne("InternalChat.Domain.Conversations.Conversation", null)
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_read_state_conversation_conversation_id");

                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_read_state_employee_employee_id");
                });

            modelBuilder.Entity("InternalChat.Infrastructure.Persistence.Notifications.PushSubscriptionRecord", b =>
                {
                    b.HasOne("InternalChat.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_push_subscription_employee_employee_id");
                });
#pragma warning restore 612, 618
        }
    }
}
