using System.Security.Cryptography;
using InternalChat.Domain.Common;

namespace InternalChat.Domain.Messages;

/// <summary>
/// The sender's idempotency key: a ULID generated by the client before the first send attempt.
/// </summary>
/// <remarks>
/// <para>
/// research.md D1 and FR-011. The unique index on <c>(conversation_id, client_message_key)</c> is
/// <em>the entire</em> exactly-once guarantee — a retried send hits the constraint and the handler
/// returns the existing message rather than inserting a second one. Everything that makes that work
/// depends on the client reproducing the same key across retries, which is why a malformed key is
/// refused here rather than stored: a key the client cannot reproduce would silently duplicate the
/// message on the next attempt.
/// </para>
/// <para>
/// <b>Case-insensitive by specification.</b> Crockford base32 folds case, and clients differ on
/// which they emit. Two keys differing only in case are the same key; treating them as different
/// would let a retry from a client that changed case produce a duplicate — the one outcome FR-011
/// forbids.
/// </para>
/// </remarks>
public sealed class ClientMessageKey : ValueObject
{
    /// <summary>A ULID is always 26 characters of Crockford base32.</summary>
    public const int Length = 26;

    /// <summary>
    /// Crockford base32: the digits, and the letters minus I, L, O, and U.
    /// </summary>
    /// <remarks>
    /// I, L, and O are excluded because they are visually confusable with 1 and 0; U is excluded to
    /// avoid accidental obscenities. Their absence is what makes an otherwise-plausible 26-character
    /// string detectably not a ULID.
    /// </remarks>
    private const string Alphabet = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

    private ClientMessageKey(string value) => Value = value;

    /// <summary>The key, upper-cased so equality and the database index agree.</summary>
    public string Value { get; }

    /// <summary>
    /// Parses a client-supplied key.
    /// </summary>
    /// <exception cref="ArgumentException">The value is not a well-formed ULID.</exception>
    public static ClientMessageKey Parse(string? value)
    {
        string candidate = value?.Trim().ToUpperInvariant() ?? string.Empty;

        if (candidate.Length != Length)
        {
            throw new ArgumentException(
                $"A client message key is a {Length}-character ULID; this one is {candidate.Length} "
                + "characters. The key is the sender's idempotency key (FR-011), so a malformed one "
                + "is refused rather than stored.",
                nameof(value));
        }

        foreach (char character in candidate)
        {
            if (!Alphabet.Contains(character, StringComparison.Ordinal))
            {
                throw new ArgumentException(
                    $"'{character}' is not a Crockford base32 character, so this is not a ULID.",
                    nameof(value));
            }
        }

        return new ClientMessageKey(candidate);
    }

    /// <summary>Whether a value is a well-formed key, without throwing.</summary>
    public static bool TryParse(string? value, out ClientMessageKey? key)
    {
        try
        {
            key = Parse(value);
            return true;
        }
        catch (ArgumentException)
        {
            key = null;
            return false;
        }
    }

    /// <summary>
    /// Generates a key.
    /// </summary>
    /// <remarks>
    /// <b>Not used on the production send path</b> — the client supplies the key, and a
    /// server-generated one would make every retry a new message, which is the opposite of what
    /// FR-011 requires. This exists for tests and the seeder, both of which need a well-formed key
    /// without a browser. The timestamp prefix keeps generated keys roughly sortable, matching a
    /// real ULID's shape so nothing downstream is tested against a key no client would send.
    /// </remarks>
    public static ClientMessageKey New()
    {
        Span<char> buffer = stackalloc char[Length];

        // 48-bit millisecond timestamp, most significant character first — 10 characters, as in a
        // real ULID.
        long timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        for (int i = 9; i >= 0; i--)
        {
            buffer[i] = Alphabet[(int)(timestamp % 32)];
            timestamp /= 32;
        }

        Span<byte> random = stackalloc byte[Length - 10];
        RandomNumberGenerator.Fill(random);

        for (int i = 0; i < random.Length; i++)
        {
            buffer[10 + i] = Alphabet[random[i] % 32];
        }

        return new ClientMessageKey(new string(buffer));
    }

    /// <inheritdoc />
    protected override IEnumerable<object?> GetEqualityComponents()
    {
        yield return Value;
    }

    /// <inheritdoc />
    public override string ToString() => Value;
}
